#!/usr/bin/env ruby
require 'rubygems'
require 'rake'
require 'rake/testtask'
require 'rake/rdoctask'
require 'rake/gempackagetask'
require 'rake/contrib/rubyforgepublisher'

PKG_VERSION = "1.3.0"
PKG_NAME = "theme_generator"
PKG_FILE_NAME = "#{PKG_NAME}-#{PKG_VERSION}"
PKG_SUMMARY = "[Rails] Theme generator adds support for themes into Rails applications"

PKG_FILES = FileList[
    "templates/*", "[A-Z]*", "theme_generator.rb"
].exclude(/\bCVS\b|~$|\.svn/)

desc "Default Task"
task :default => [ :lines ]

task :syntax do 
  filelist = Dir.glob('**/*.rb')
  filelist.each do |file|
    output = `ruby -c #{file}`
    unless output =~ /Syntax OK/
      puts "#{file}:"
      puts "  #{output}"
      return 
    end
  end
  puts 'Syntax OK'  
end

# Generate the RDoc documentation
Rake::RDocTask.new { |rdoc|
  rdoc.rdoc_dir = 'doc'
  rdoc.title    = "Theme Generator"
  rdoc.options << '--line-numbers --inline-source'
  rdoc.rdoc_files.include('templates/*.rb', 'templates/README')
}

task :lines do
  lines = 0
  codelines = 0
  Dir.foreach("templates") { |file_name| 
    next unless file_name =~ /.*rb/
    
    f = File.open("templates/" + file_name)

    while line = f.gets
      lines += 1
      next if line =~ /^\s*$/
      next if line =~ /^\s*#/
      codelines += 1
    end
  }
  puts "Lines #{lines}, LOC #{codelines}"
end

spec = Gem::Specification.new do |s|
  s.author = 'M@ McCray'
  s.email = 'darthapo@gmail.com'
  s.homepage = 'http://www.mattmccray.com'

  s.name = PKG_NAME
  s.version = PKG_VERSION
  s.summary = PKG_SUMMARY
  
  s.has_rdoc = false
  s.files = PKG_FILES
end

Rake::GemPackageTask.new(spec) do |p|
  #puts "  File List:" 
  #puts "   - #{PKG_FILES.join("\n   - ")}"
  p.gem_spec = spec
  p.need_tar = true
  p.need_zip = true
end

# --- Ruby forge release manager by florian gross -------------------------------------------------
RUBY_FORGE_PROJECT = 'theme-generator'
RUBY_FORGE_USER = 'darthapo'
RELEASE_NAME  = "REL #{PKG_VERSION}"

desc "Publish the release files to RubyForge."
task :release => [:gem] do
  files = ["gem"].map { |ext| "pkg/#{PKG_FILE_NAME}.#{ext}" }

  if RUBY_FORGE_PROJECT then
    require 'net/http'
    require 'open-uri'

    project_uri = "http://rubyforge.org/projects/#{RUBY_FORGE_PROJECT}/"
    project_data = open(project_uri) { |data| data.read }
    group_id = project_data[/[?&]group_id=(\d+)/, 1]
    raise "Couldn't get group id" unless group_id

    # This echos password to shell which is a bit sucky
    if ENV["RUBY_FORGE_PASSWORD"]
      password = ENV["RUBY_FORGE_PASSWORD"]
    else
      print "#{RUBY_FORGE_USER}@rubyforge.org's password: "
      password = STDIN.gets.chomp
    end

    login_response = Net::HTTP.start("rubyforge.org", 80) do |http|
      data = [
        "login=1",
        "form_loginname=#{RUBY_FORGE_USER}",
        "form_pw=#{password}"
      ].join("&")
      http.post("/account/login.php", data)
    end

    cookie = login_response["set-cookie"]
    raise "Login failed" unless cookie
    headers = { "Cookie" => cookie }

    release_uri = "http://rubyforge.org/frs/admin/?group_id=#{group_id}"
    release_data = open(release_uri, headers) { |data| data.read }
    package_id = release_data[/[?&]package_id=(\d+)/, 1]
    raise "Couldn't get package id" unless package_id

    first_file = true
    release_id = ""

    files.each do |filename|
      basename  = File.basename(filename)
      file_ext  = File.extname(filename)
      file_data = File.open(filename, "rb") { |file| file.read }

      puts "Releasing #{basename}..."

      release_response = Net::HTTP.start("rubyforge.org", 80) do |http|
        release_date = Time.now.strftime("%Y-%m-%d %H:%M")
        type_map = {
          ".zip"    => "3000",
          ".tgz"    => "3110",
          ".gz"     => "3110",
          ".gem"    => "1400"
        }; type_map.default = "9999"
        type = type_map[file_ext]
        boundary = "rubyqMY6QN9bp6e4kS21H4y0zxcvoor"

        query_hash = if first_file then
          {
            "group_id" => group_id,
            "package_id" => package_id,
            "release_name" => RELEASE_NAME,
            "release_date" => release_date,
            "type_id" => type,
            "processor_id" => "8000", # Any
            "release_notes" => "",
            "release_changes" => "",
            "preformatted" => "1",
            "submit" => "1"
          }
        else
          {
            "group_id" => group_id,
            "release_id" => release_id,
            "package_id" => package_id,
            "step2" => "1",
            "type_id" => type,
            "processor_id" => "8000", # Any
            "submit" => "Add This File"
          }
        end

        query = "?" + query_hash.map do |(name, value)|
          [name, URI.encode(value)].join("=")
        end.join("&")

        data = [
          "--" + boundary,
          "Content-Disposition: form-data; name=\"userfile\"; filename=\"#{basename}\"",
          "Content-Type: application/octet-stream",
          "Content-Transfer-Encoding: binary",
          "", file_data, ""
          ].join("\x0D\x0A")

        release_headers = headers.merge(
          "Content-Type" => "multipart/form-data; boundary=#{boundary}"
        )

        target = first_file ? "/frs/admin/qrs.php" : "/frs/admin/editrelease.php"
        http.post(target + query, data, release_headers)
      end

      if first_file then
        release_id = release_response.body[/release_id=(\d+)/, 1]
        raise("Couldn't get release id") unless release_id
      end

      first_file = false
    end
  end
end
